{{ if .Values.persistence.claim.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "grafeas.fullname" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.claimSize }}
{{ end }}